### ISSUE TITLE
部分示例代码未显示

### ISSUE THREAD

**Issue by seisman** [JuliaCN/julia_zh_cn#44]
比如[变量](http://julia-cn.readthedocs.org/zh_CN/latest/manual/variables/)这一节，源代码为
~~~ rst
A variable, in Julia, is a name associated (or bound) to a value. It's useful when you 
want to store a value (that you obtained after some math, for example) for later use. 
For example:

.. doctest::

    # Assign the value 10 to the variable x
    julia> x = 10 
    10
    
    # Doing math with x's value
    julia> x + 1
    11
    
    # Reassign x's value
    julia> x = 1 + 1 
    2
    
    # You can assign values of other types, like strings of text
    julia> x = "Hello World!"
    "Hello World!"

Julia 提供了极其灵活的变量命名系统。变量名区分大小写。
~~~
GitHub的[渲染效果](https://github.com/JuliaCN/julia_zh_cn/blob/master/manual/variables.rst)为：
![selection_007](https://cloud.githubusercontent.com/assets/3974108/10656001/f1f3c764-78ac-11e5-96de-1c9d75447b30.png)

[中文文档](http://julia-cn.readthedocs.org/zh_CN/latest/manual/variables/)的渲染类似，也是没有代码部分：
![selection_008](https://cloud.githubusercontent.com/assets/3974108/10656031/38c0bdc8-78ad-11e5-8d7d-bb70fc7ae73b.png)

似乎是RTFD在解释`doctest`时出问题了。

而官方英文文档里近似同样的代码却可以[正确渲染](http://docs.julialang.org/en/latest/manual/variables/)：
![selection_009](https://cloud.githubusercontent.com/assets/3974108/10656060/a1dc14c4-78ad-11e5-8054-0f55843a2943.png)

**Comment by cuiweiqiang** [comment]
@seisman 有个临时解决的方案，把julia的项目源代码clone下来，然后将本项目的manual下的文件替换julia项目下的doc/manual中的文件，然后在julia下编译就行。

**Comment by GaZ3ll3** [comment]
这是两个问题, 一个是 conf.py 里面应该改为, 这样sphinx可以看见这个doctest builder.

```
extensions = ['sphinx.ext.mathjax',
              'juliadoc.julia',
              'juliadoc.jldoctest',
              'juliadoc.jlhelp']
```

另一个是我们的juliadoc 很久没更新, 我尝试了下用我们自己的repo(pip install), 发现import都会失败. 我改为 
```
-e git+https://github.com/JuliaLang/JuliaDoc.git@85c83a5c4ecd1716e0aa858d73322cc2058bc7b1#egg=JuliaDoc
```
之后就可以import,虽然会报一些错, 但是最后编译都没有问题. 所以我觉得minimal的方案是
1. 改conf.py
2. 改requirements.txt

我打算再调试下各种组合, 再提交一个方案.

**Comment by GaZ3ll3** [comment]
http://test-julia-3.readthedocs.org/zh_CN/latest/manual/variables/

这里是我这样修改的结果.

**Comment by cuiweiqiang** [comment]
@GaZ3ll3 这个版本好像有个问题，左侧导航栏不能随页面滚动。具体原因还在看。

**Comment by GaZ3ll3** [comment]
目测是因为没把juliadoc的模版更新。主要的module都已经和官方一致。我晚一些再试试。

**Comment by GaZ3ll3** [comment]
@cuiweiqiang 摊手, 我尝试过把conf改过, 也尝试把template文件夹去掉, 都没有用.

**Comment by GaZ3ll3** [comment]
文档已经更新, sidebar的问题还是无法解决. 决定重新开一个issue讨论.
