### ISSUE TITLE
github里面的文档版本没有更新到read the docs

### ISSUE THREAD

**Issue by gangchen** [JuliaCN/julia_zh_cn#51]
看上去，Read the Docs上的版本落后github不少了

**Comment by GaZ3ll3** [comment]
好像是webhook的问题, 一直显示cloning.

**Comment by Roger-luo** [comment]
@morvinzha 看看你merge的有没有被正确显示?

**Comment by morvinzha** [comment]
@Roger-luo 有两个行内代码显示的有点问题，我这两天把后面的翻译完一起改掉

**Comment by Roger-luo** [comment]
@GaZ3ll3 我新merge进来的部分也一直没有正确显示，具体是啥错误？

**Comment by GaZ3ll3** [comment]
@Roger-luo  error is 

"
Failed to import project: Failed to get code from 'https://github.com/JuliaCN/julia_zh_cn' (git clone): 1 git clone error output: No submodule mapping found in .gitmodules for path 'JuliaDoc-1' 
"
seems like submodule's problem. I will look into it.
