### ISSUE TITLE
[JulialangOrgCN] Nice to meet great works here; Welcome to JulialangOrgCN.

### ISSUE THREAD

**Issue by nagexiucai** [JuliaCN/julia_zh_cn#64]
Hi,

With great honor that [@JulialangOrgCN](https://github.com/JulialangOrgCN) has been another Julia Chinese(Simplified) community.
Because of julialang.cn had been offline for a long time.
Works under JuliaCN are very well and will fork into @JulialangOrgCN later.
Welcome to join @JulialangOrgCN and do any constructive things for @JulialangOrgCN.

Regards!

**Comment by i2000s** [comment]
Is this problem cannot be fixed within this org?

**Comment by Roger-luo** [comment]
@i2000s 我已经答复了他的邮件. 在1.0之前JuliaCN可能不会很活跃, 中文用户也较少, 人手不足, 所以文档和主页都没有在维护. 另外新建一个org无助于解决问题.

恕我直言, @JulialangOrgCN 目前看起来只是一个学生习作的状态,即便没有JuliaCN的存在也不值得contribute. talk is cheap!
