### ISSUE TITLE
Julia中文文档翻译任务列表

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/julia_zh_cn#65]
## Manual
- [x]  [Introduction](@ref man-introduction)
- [x]  [Getting Started](@ref)
- [x]  [Variables](@ref)
- [x]  [Integers and Floating-Point Numbers](@ref)
- [x]  [Mathematical Operations and Elementary Functions](@ref)
- [ ]  [Complex and Rational Numbers](@ref)
- [x]  [Strings](@ref man-strings)
- [ ]  [Functions](@ref man-functions)
- [ ]  [Control Flow](@ref)
- [ ]  [Scope of Variables](@ref scope-of-variables)
- [ ]  [Types](@ref man-types)
- [ ]  [Methods](@ref)
- [ ]  [Constructors](@ref man-constructors)
- [ ]  [Conversion and Promotion](@ref conversion-and-promotion)
- [ ]  [Interfaces](@ref)
- [ ]  [Modules](@ref modules)
- [ ]  [Documentation](@ref)
- [ ]  [Metaprogramming](@ref)
- [ ]  [Multi-dimensional Arrays](@ref man-multi-dim-arrays)
- [x]  [Linear Algebra](@ref)
- [ ]  [Networking and Streams](@ref)
- [ ]  [Parallel Computing](@ref)
- [ ]  [Date and DateTime](@ref)
- [ ]  [Running External Programs](@ref)
- [ ]  [Calling C and Fortran Code](@ref)
- [ ]  [Handling Operating System Variation](@ref)
- [ ]  [Environment Variables](@ref)
- [ ]  [Interacting With Julia](@ref)
- [ ]  [Embedding Julia](@ref)
- [ ]  [Packages](@ref)
- [ ]  [Profiling](@ref)
- [x]  [Stack Traces](@ref)
- [x]  [Performance Tips](@ref man-performance-tips)
- [ ]  [Workflow Tips](@ref man-workflow-tips)
- [x]  [Style Guide](@ref)
- [ ]  [Frequently Asked Questions](@ref)
- [ ]  [Noteworthy Differences from other Languages](@ref)
- [ ]  [Unicode Input](@ref)

Note: see #70

**Comment by hopesAccount** [comment]
Linear Algebra

**Comment by KortanZ** [comment]
Stack Traces

**Comment by hopesAccount** [comment]
参照的文档规范部分  要求跟进tag0.5.0的翻译  能不能给一下现在要求跟进的版本tag

**Comment by Roger-luo** [comment]
我们直接跟进最新的文档吧．Manual的部分变化不大，直接翻译master里的．现在目标是能在1.0出来的同时有中文文档用．

**Comment by KortanZ** [comment]
最新文档我看好像改用markdown写了，仍然转成rst是吗

**Comment by Roger-luo** [comment]
我们也改成markdown吧，直接先在这个ｒepo里新建对应的文件．　我来看看怎么在readthedocs改成markdown.

**Comment by Roger-luo** [comment]
@GaZ3ll3 现在readthedocs的账号是怎么管理的？我找不到了好像．我们看看怎么跟上master分支改成markdown吧．

**Comment by KortanZ** [comment]
这样的话文档规范那边有时间就做个调整吧

**Comment by hopesAccount** [comment]
还有一个问题是 官方master的文件目录结构变了  这边的怎么办

**Comment by Roger-luo** [comment]
manual文件夹里面的还没有变，我们先保持ｊｕｌｉａ_cn_doc原来的结构吧．等@GaZ3II3回复了我再看怎么把新版本的文档给弄到ｒｅadthedocs里去．

**Comment by hopesAccount** [comment]
有个问题，在master分支里没有linear-Algebra的md文件 但是官方文档里有。。

**Comment by Roger-luo** [comment]
在stdlib里，有一些被挪过去了，我们先翻译后面再整理．

**Comment by hopesAccount** [comment]
好的  那我就先按照这个表格翻译 在stdlib的 我拿过来吧

**Comment by sunoru** [comment]
领一下 Style Guide

**Comment by KortanZ** [comment]
Performance Tips

**Comment by sunoru** [comment]
Getting Started

**Comment by Roger-luo** [comment]
Introduction

**Comment by sunoru** [comment]
Variables

**Comment by hopesAccount** [comment]
Mathematical Operations and Elementary Functions

**Comment by sunoru** [comment]
Integers and Floating-Point Numbers

**Comment by sunoru** [comment]
Complex and Rational Numbers

**Comment by sunoru** [comment]
Strings

**Comment by GaZ3ll3** [comment]
@Roger-luo sorry，我很久没来看一眼。 readthedocs是 @wlbksy 的帐号底下的。 我以前有过一段时间的权限，后来readthedocs抽风了，一直编译不了，然后他重新建了一个 （如果我没记错的话）。

**Comment by Roger-luo** [comment]
@GaZ3ll3 谢谢，我现在找到readthedocs了，但是目前我们已经挪到了JuliaCN.jl下以支持Documenter.jl，参见repo下的issue。

**Comment by Roger-luo** [comment]
我先关闭这个issue吧，我刚刚到北京，之后会开始着手让JuliaCN.jl能够工作起来，然后之后就直接在JuliaCN.jl里增加翻译吧。
